services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - kong-net
    
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kong-net
    
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - kong-net
    
  userservice:
    image: user-service
    container_name: user-service
    ports:
      - '9810:9810'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    depends_on:
      - kafka
      - mysql
      - authservice
    networks:
      - kong-net
   
  expenseservice:
    image: expense-service
    container_name: expense-service
    ports: 
      - '9820:9820'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: expenseservice
    depends_on:
      - kafka
      - mysql
      - authservice
    networks:
      - kong-net

  parserservice:
    image: parser-service
    container_name: parser-service
    ports:
      - '8010:8010'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    depends_on:
      - kafka
      - mysql
      - authservice
    networks:
      - kong-net

  authservice:
    image: auth-service
    container_name: auth-service
    ports:
      - '9898:9898'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: authservice
    depends_on:
      - kafka
      - mysql
    networks:
      - kong-net

  kong:
    image: kong-custom
    container_name: kong-custom
    ports:
      - "8000:8000"   
      - "8443:8443"   
      - "8001:8001"  
    environment:
      - KONG_DATABASE=off
      - KONG_PORTAL=off
      - KONG_PLUGINS=bundled,custom-auth
      - KONG_LOG_LEVEL=debug
      - KONG_CONFIGURATION=/etc/kong/kong.yml
      - KONG_PREFIX=/usr/local/kong
    volumes:
      - ./kong-APIGateway/custom-plugins:/usr/local/kong/plugins
      - ./kong-APIGateway/config/kong.yml:/etc/kong/kong.yml
    networks:
      - kong-net

volumes:
  mysql-db:
    driver: local

networks:
  kong-net:
    driver: bridge